### ISSUE TITLE
目前啥收益，假设单台3090或者3080ti

### ISSUE THREAD

**Issue by UrsaSense** [CoolkHz/orz-cli-gpu#1]
感谢分享

**Comment by CoolkHz** [comment]
3090 这种卡跑浪费，最好弄a4000 这种纯计算单元的卡，不过 3090 这种也行， 跑几百个号都没问题。
瓶颈在 rpc ，  要搞尽可能多的 rpc，如果你的 rpc没有并发限制 就不用搞多，50 个号目前一小时 1 个 orz。

**Comment by UrsaSense** [comment]
好的呀，换算成人民币一小时单卡大概多少钱。有完整教程吗，例如配置钱包啥的，刚接触这个币

**Comment by UrsaSense** [comment]
STAR了

**Comment by CoolkHz** [comment]
换算成人民币得看 orz 币价如何了，
刚接触的话你可以去用 cpu 版本  gpu 有点门槛 需要配置驱动和 cuda 工具包之类的。
https://coolkhz.xlog.app/ORZ-wa-kuang-CPU-duo-hao-jiao-cheng
